<?php

echo $this->doctype();
?>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <title>Execução de Crawlers - Web</title>
    <style type="text/css">
        body {
            font-family: "Courier", "Arial";
            background: #000;
            color: #00aa00;
            font-size: 12px;
            margin: 0 auto;
        }

        .console {
            padding: 10px;
            border: 1px solid #444;
            margin: 5px;
            min-width: 980px;
            overflow: auto;
        }
    </style>
</head>
<body>
<div class="console">
    <?php

    echo "<pre>" . $conteudo . "</pre>";
    ?>
</div>
</body>
</html>
